/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe: reports that the process is up and serving requests.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Job
         * @description The job, if the user requested its topic.
         */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The signed-in user's profile.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Topics
         * @description Topics whose title or slug contains `q` (trimmed, 1 to 80 characters), by title.
         */
        get: operations["list_topics"];
        put?: never;
        /**
         * Request Topic
         * @description The registry topic the query names: the one that exists, or a new one (module docstring).
         */
        post: operations["create_topic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Topic
         * @description The topic; its end state and milestones once it is `ready`.
         */
        get: operations["get_topic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{slug}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Tree
         * @description The topic's nodes in topological order with the user's mastery, and its edges.
         */
        get: operations["get_topic_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorBody
         * @description The shape of every fixed body, `{"detail": "..."}`, for the OpenAPI document.
         */
        ErrorBody: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description `GET /jobs/{id}`: a job's kind, status, progress and the reason it failed or was retried.
         */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string | null;
            status: components["schemas"]["JobState"];
        };
        /** @enum {string} */
        JobState: "queued" | "running" | "done" | "failed";
        /**
         * Milestone
         * @description A milestone's id, position and title; its rubric and checks come with the checkpoint.
         */
        Milestone: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Title */
            title: string;
        };
        /**
         * Profile
         * @description A user's profile, as `GET /me` returns it.
         */
        Profile: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Daily Minutes */
            daily_minutes: number;
            /** Display Name */
            display_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Push Time */
            push_time: string | null;
            /** Timezone */
            timezone: string;
        };
        /** @description Trimmed, 1 to 80 characters, no control character */
        QueryText: string;
        /**
         * TopicCreated
         * @description `POST /topics`: the topic, and its new ingestion job's id (`null` when it existed).
         */
        TopicCreated: {
            /** Job Id */
            job_id: string | null;
            topic: components["schemas"]["TopicSummary"];
        };
        /**
         * TopicDetail
         * @description `GET /topics/{slug}`: `end_state` is null and `milestones` empty until it is `ready`.
         */
        TopicDetail: {
            /** Description */
            description: string | null;
            /** End State */
            end_state: string | null;
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            /** Slug */
            slug: string;
            status: components["schemas"]["TopicStatus"];
            /** Title */
            title: string;
        };
        /**
         * TopicList
         * @description `GET /topics`.
         */
        TopicList: {
            /** Topics */
            topics: components["schemas"]["TopicSummary"][];
        };
        /**
         * TopicRequest
         * @description `POST /topics`: what the user typed, to be matched against the registry.
         */
        TopicRequest: {
            query: components["schemas"]["QueryText"];
        };
        /** @enum {string} */
        TopicStatus: "pending" | "ingesting" | "synthesizing" | "ready" | "failed";
        /**
         * TopicSummary
         * @description A topic in a list, or the topic `POST /topics` found or created.
         */
        TopicSummary: {
            /** Description */
            description: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["TopicStatus"];
            /** Title */
            title: string;
        };
        /**
         * TopicTree
         * @description `GET /topics/{slug}/tree`: nodes in topological order.
         */
        TopicTree: {
            /** Edges */
            edges: components["schemas"]["TreeEdge"][];
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            /** Nodes */
            nodes: components["schemas"]["TreeNode"][];
            topic: components["schemas"]["TreeTopic"];
        };
        /**
         * TreeEdge
         * @description An edge from one node of the topic to another: `from` comes before `to`.
         */
        TreeEdge: {
            /** From */
            from: string;
            /** Kind */
            kind: string;
            /** To */
            to: string;
        };
        /**
         * TreeNode
         * @description A node, with the user's mastery (0 to 1) and whether its prerequisites are mastered.
         */
        TreeNode: {
            /** Estimated Minutes */
            estimated_minutes: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mastery */
            mastery: number;
            /** Milestone Id */
            milestone_id: string | null;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Unlocked */
            unlocked: boolean;
        };
        /**
         * TreeTopic
         * @description The topic of a tree.
         */
        TreeTopic: {
            /** Description */
            description: string | null;
            /** End State */
            end_state: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["TopicStatus"];
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_topics: {
        parameters: {
            query: {
                q: components["schemas"]["QueryText"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_topic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicRequest"];
            };
        };
        responses: {
            /** @description The topic exists; no job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicCreated"];
                };
            };
            /** @description The topic is created and its ingestion queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicCreated"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Topic not supported, or a request of the wrong shape */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"] | components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    /** @description Seconds */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_topic_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicTree"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
