/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cards/{card_id}/attempt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attempt Card
         * @description Grade, record and schedule an answer to a card of the user's feed (module docstring).
         */
        post: operations["attempt_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed Next
         * @description The next set of today, once every card of the current one has an attempt.
         */
        get: operations["get_feed_next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed Summary
         * @description What a stored set's recorded attempts did: the nodes moved and the progress gained.
         */
        get: operations["get_feed_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed Today
         * @description Today's set: the lowest one with an unanswered card, else set 1.
         */
        get: operations["get_feed_today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe: reports that the process is up and serving requests.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Job
         * @description The job, if the user requested its topic.
         */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The signed-in user's profile.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Update the signed-in user's profile; a field left out is not changed.
         */
        patch: operations["update_me"];
        trace?: never;
    };
    "/me/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Enrollments
         * @description The user's enrollments, oldest first.
         */
        get: operations["list_enrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Topics
         * @description Topics whose title or slug contains `q` (trimmed, 1 to 80 characters), by title.
         */
        get: operations["list_topics"];
        put?: never;
        /**
         * Request Topic
         * @description The registry topic the query names: the one that exists, or a new one (module docstring).
         */
        post: operations["create_topic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Topic
         * @description The topic; its end state and milestones once it is `ready`.
         */
        get: operations["get_topic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{slug}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll Topic
         * @description Enroll in the topic, or read the enrollment that exists (module docstring).
         */
        post: operations["enroll_topic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{slug}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Tree
         * @description The topic's nodes in topological order with the user's mastery, and its edges.
         */
        get: operations["get_topic_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttemptNode
         * @description The attempted card's node: its title, and the user's mastery of it before and after.
         */
        AttemptNode: {
            mastery_after: components["schemas"]["Fraction"];
            mastery_before: components["schemas"]["Fraction"];
            /** Title */
            title: string;
        };
        /**
         * AttemptRequest
         * @description `POST /cards/{id}/attempt`.
         */
        AttemptRequest: {
            /**
             * Client Attempt Id
             * Format: uuid
             */
            client_attempt_id: string;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Feed Date
             * Format: date
             */
            feed_date: string;
            response: components["schemas"]["AttemptResponse"];
            /** Set Number */
            set_number: number;
        };
        AttemptResponse: components["schemas"]["ChoiceAnswer"] | components["schemas"]["CodeAnswer"] | components["schemas"]["RatingAnswer"] | components["schemas"]["SeenAnswer"];
        /**
         * AttemptResult
         * @description What an attempt did (module docstring).
         */
        AttemptResult: {
            /** Correct */
            correct: boolean | null;
            /** Feedback */
            feedback: string | null;
            /** Next Due */
            next_due: string | null;
            node: components["schemas"]["AttemptNode"];
            rating: components["schemas"]["Rating"] | null;
            /** Score */
            score: number | null;
        };
        Card: components["schemas"]["ConceptCard"] | components["schemas"]["QuizCard"] | components["schemas"]["PredictCard"] | components["schemas"]["ExerciseCard"] | components["schemas"]["ReviewCard"] | components["schemas"]["CheckpointCard"];
        /** CheckpointCard */
        CheckpointCard: {
            /** Est Seconds */
            est_seconds: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Milestone */
            milestone: number;
            /** Milestone Count */
            milestone_count: number;
            /** Pass Threshold */
            pass_threshold: number;
            /** Rubric */
            rubric: components["schemas"]["RubricRow"][];
            /** Starter Code */
            starter_code: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "checkpoint";
        };
        /**
         * ChoiceAnswer
         * @description A quiz or predict card's answer: the index of the option chosen.
         */
        ChoiceAnswer: {
            /** Choice */
            choice: number;
        };
        Code: string;
        /**
         * CodeAnswer
         * @description An exercise's answer: the learner's code.
         */
        CodeAnswer: {
            /** Code */
            code: string;
        };
        /** ConceptCard */
        ConceptCard: {
            /** Body */
            body: string;
            /** Cycles */
            cycles: string[];
            /** Est Seconds */
            est_seconds: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Node */
            node: string;
            /** Snippet */
            snippet: string;
            /** Snippet Comment */
            snippet_comment: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "concept";
        };
        /**
         * ContainsCheck
         * @description The learner's code must contain `value`; with `ignore_whitespace`, once all whitespace is
         *     removed from both.
         */
        ContainsCheck: {
            /** Ignore Whitespace */
            ignore_whitespace: boolean;
            /**
             * Kind
             * @constant
             */
            kind: "contains";
            value: components["schemas"]["Code"];
        };
        /**
         * EnrollRequest
         * @description `POST /topics/{slug}/enroll`.
         */
        EnrollRequest: {
            /**
             * Daily Minutes
             * @default 10
             */
            daily_minutes: number;
            /**
             * Horizon Days
             * @default 14
             */
            horizon_days: number;
        };
        /**
         * Enrollment
         * @description A user's enrollment in a topic.
         */
        Enrollment: {
            /** Daily Minutes */
            daily_minutes: number;
            /** Horizon Days */
            horizon_days: number;
            /** Progress */
            progress: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["EnrollmentStatus"];
            /** Topic Slug */
            topic_slug: string;
            /** Topic Title */
            topic_title: string;
        };
        /**
         * EnrollmentList
         * @description `GET /me/enrollments`: oldest first.
         */
        EnrollmentList: {
            /** Enrollments */
            enrollments: components["schemas"]["Enrollment"][];
        };
        /** @enum {string} */
        EnrollmentStatus: "active" | "paused" | "completed";
        /**
         * ErrorBody
         * @description The shape of every fixed body, `{"detail": "..."}`, for the OpenAPI document.
         */
        ErrorBody: {
            /** Detail */
            detail: string;
        };
        /** ExerciseCard */
        ExerciseCard: {
            /** Checks */
            checks: components["schemas"]["ContainsCheck"][];
            /** Est Seconds */
            est_seconds: number;
            /** Fail Msg */
            fail_msg: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lang */
            lang: string;
            /** Node */
            node: string;
            /** Pass Msg */
            pass_msg: string;
            /** Starter Code */
            starter_code: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "exercise";
        };
        /**
         * FeedSet
         * @description `GET /feed/today` and `GET /feed/next`. An attempt at one of its cards names the set by
         *     `feed_date` and `set_number`.
         */
        FeedSet: {
            /** Cards */
            cards: components["schemas"]["Card"][];
            /**
             * Feed Date
             * Format: date
             */
            feed_date: string;
            /** Set Number */
            set_number: number;
            summary: components["schemas"]["Summary"];
            topic: components["schemas"]["FeedTopic"];
        };
        /**
         * FeedTopic
         * @description The topic, with the user's day of the enrollment (from 1), streak and progress.
         */
        FeedTopic: {
            /** Day */
            day: number;
            /** Horizon Days */
            horizon_days: number;
            progress: components["schemas"]["Fraction"];
            /** Slug */
            slug: string;
            /** Streak */
            streak: number;
            /** Title */
            title: string;
        };
        Fraction: number;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description `GET /jobs/{id}`: a job's kind, status, progress and the reason it failed or was retried.
         */
        Job: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string | null;
            status: components["schemas"]["JobState"];
        };
        /** @enum {string} */
        JobState: "queued" | "running" | "done" | "failed";
        /**
         * Milestone
         * @description A milestone's id, position and title; its rubric and checks come with the checkpoint.
         */
        Milestone: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Position */
            position: number;
            /** Title */
            title: string;
        };
        /** PredictCard */
        PredictCard: {
            /** Code */
            code: string;
            /** Correct */
            correct: number;
            /** Est Seconds */
            est_seconds: number;
            /** Explanation */
            explanation: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Node */
            node: string;
            /** Options */
            options: string[];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "predict";
        };
        /**
         * Profile
         * @description A user's profile, as `GET /me` returns it.
         */
        Profile: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Daily Minutes */
            daily_minutes: number;
            /** Display Name */
            display_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Push Time */
            push_time: string | null;
            /** Timezone */
            timezone: string;
        };
        /**
         * ProfileUpdate
         * @description `PATCH /me`: the fields to change, one to four; a field left out is not changed.
         */
        ProfileUpdate: {
            /** Daily Minutes */
            daily_minutes?: number;
            /** Display Name */
            display_name?: string | null;
            /** Push Time */
            push_time?: string | null;
            /**
             * Timezone
             * @description An IANA timezone name
             */
            timezone?: string;
        };
        /** @description Trimmed, 1 to 80 characters, no control character */
        QueryText: string;
        /** QuizCard */
        QuizCard: {
            /** Correct */
            correct: number;
            /** Est Seconds */
            est_seconds: number;
            /** Explanation */
            explanation: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Node */
            node: string;
            /** Options */
            options: string[];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "quiz";
        };
        /** @enum {string} */
        Rating: "again" | "hard" | "good" | "easy";
        /**
         * RatingAnswer
         * @description A review card's answer: how well the learner recalled it.
         */
        RatingAnswer: {
            rating: components["schemas"]["Rating"];
        };
        /** ReviewCard */
        ReviewCard: {
            /** Answer */
            answer: string;
            /** Est Seconds */
            est_seconds: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Seen Days */
            last_seen_days: number;
            /** Node */
            node: string;
            /** Prompt */
            prompt: string;
            /** Ratings */
            ratings: [
                string,
                string
            ][];
            /** Snippet */
            snippet: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "review";
        };
        /**
         * RubricRow
         * @description One check of a checkpoint: a label, and the pattern the learner's code must match.
         */
        RubricRow: {
            /** Label */
            label: string;
            /** Regex */
            regex: string;
        };
        /**
         * SeenAnswer
         * @description A concept card's answer: it was read.
         */
        SeenAnswer: {
            /**
             * Seen
             * @constant
             */
            seen: true;
        };
        /**
         * Summary
         * @description What the set would do if every card were answered correctly (K12's projected summary), in
         *     `FeedSet`; what its recorded attempts did, in `GET /feed/summary` (M3 plan, Task 11).
         */
        Summary: {
            /** Moved */
            moved: [
                string,
                components["schemas"]["Fraction"],
                components["schemas"]["Fraction"]
            ][];
            /** Progress Delta */
            progress_delta: number;
            /** Reminder */
            reminder: string;
            /** Title */
            title: string;
            /** Tomorrow */
            tomorrow: string;
        };
        /**
         * TopicCreated
         * @description `POST /topics`: the topic, and its new ingestion job's id (`null` when it existed).
         */
        TopicCreated: {
            /** Job Id */
            job_id: string | null;
            topic: components["schemas"]["TopicSummary"];
        };
        /**
         * TopicDetail
         * @description `GET /topics/{slug}`: `end_state` is null and `milestones` empty until it is `ready`.
         */
        TopicDetail: {
            /** Description */
            description: string | null;
            /** End State */
            end_state: string | null;
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            /** Slug */
            slug: string;
            status: components["schemas"]["TopicStatus"];
            /** Title */
            title: string;
        };
        /**
         * TopicList
         * @description `GET /topics`.
         */
        TopicList: {
            /** Topics */
            topics: components["schemas"]["TopicSummary"][];
        };
        /**
         * TopicRequest
         * @description `POST /topics`: what the user typed, to be matched against the registry.
         */
        TopicRequest: {
            query: components["schemas"]["QueryText"];
        };
        /** @enum {string} */
        TopicStatus: "pending" | "ingesting" | "synthesizing" | "ready" | "failed";
        /**
         * TopicSummary
         * @description A topic in a list, or the topic `POST /topics` found or created.
         */
        TopicSummary: {
            /** Description */
            description: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["TopicStatus"];
            /** Title */
            title: string;
        };
        /**
         * TopicTree
         * @description `GET /topics/{slug}/tree`: nodes in topological order.
         */
        TopicTree: {
            /** Edges */
            edges: components["schemas"]["TreeEdge"][];
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            /** Nodes */
            nodes: components["schemas"]["TreeNode"][];
            topic: components["schemas"]["TreeTopic"];
        };
        /**
         * TreeEdge
         * @description An edge from one node of the topic to another: `from` comes before `to`.
         */
        TreeEdge: {
            /** From */
            from: string;
            /** Kind */
            kind: string;
            /** To */
            to: string;
        };
        /**
         * TreeNode
         * @description A node, with the user's mastery (0 to 1) and whether its prerequisites are mastered.
         */
        TreeNode: {
            /** Estimated Minutes */
            estimated_minutes: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mastery */
            mastery: number;
            /** Milestone Id */
            milestone_id: string | null;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /** Unlocked */
            unlocked: boolean;
        };
        /**
         * TreeTopic
         * @description The topic of a tree.
         */
        TreeTopic: {
            /** Description */
            description: string | null;
            /** End State */
            end_state: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["TopicStatus"];
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attempt_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResult"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not in feed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_feed_next: {
        parameters: {
            query: {
                topic: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedSet"];
                };
            };
            /** @description Nothing to serve */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Set unfinished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    /** @description Seconds */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_feed_summary: {
        parameters: {
            query: {
                topic: string;
                set: number;
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_feed_today: {
        parameters: {
            query: {
                topic: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedSet"];
                };
            };
            /** @description Nothing to serve */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_enrollments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_topics: {
        parameters: {
            query: {
                q: components["schemas"]["QueryText"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_topic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicRequest"];
            };
        };
        responses: {
            /** @description The topic exists; no job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicCreated"];
                };
            };
            /** @description The topic is created and its ingestion queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicCreated"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Topic not supported, or a request of the wrong shape */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"] | components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    /** @description Seconds */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    enroll_topic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Enrolled already; the stored enrollment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
            /** @description Enrolled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_topic_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicTree"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
