// Tests for scripts/build-strudel.mjs: the generated module's contract, repeatable output, safe
// embedding of the bundle, and the failure paths. Every build writes into a temporary folder.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, test } from 'node:test';
import vm from 'node:vm';

import { transformSync } from 'esbuild';

import { renderHtml, renderModule } from '../build-strudel.mjs';

const MOBILE = join(import.meta.dirname, '..', '..');
const SCRIPT = join(MOBILE, 'scripts', 'build-strudel.mjs');
const TEMPLATE = readFileSync(join(MOBILE, 'src', 'strudel', 'page', 'index.html'), 'utf8');
const POLICY =
  "default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' data:; " +
  "connect-src https://raw.githubusercontent.com; worker-src 'none'; base-uri 'none'; " +
  "form-action 'none'";
const NOT_FOUND = 'build-strudel: @strudel/web not found; run pnpm install\n';
const NOT_EMBEDDABLE =
  'build-strudel: the bundle contains a sequence that cannot be embedded in a script element\n';
const NOT_BUILT =
  'build-strudel: Strudel bundle not built: esbuild and @strudel/web are not installed\n';

const work = mkdtempSync(join(tmpdir(), 'build-strudel-test-'));
after(() => rmSync(work, { recursive: true, force: true }));

function run(...args) {
  return spawnSync(process.execPath, [SCRIPT, ...args], { encoding: 'utf8' });
}

// Transpiles the generated TypeScript and imports it, as the app's bundler would.
async function importModule(source) {
  const { code } = transformSync(source, { loader: 'ts', format: 'esm' });
  return import(`data:text/javascript,${encodeURIComponent(code)}`);
}

function scriptBody(html) {
  const body = html.split('<script>')[1] ?? '';
  return body.slice(0, body.indexOf('</script>'));
}

const built = { a: join(work, 'a', 'strudelHtml.ts'), b: join(work, 'b', 'strudelHtml.ts') };
const results = { a: run('--out', built.a), b: run('--postinstall', '--out', built.b) };

test('Build: writes the module with both exports, silently', async () => {
  assert.equal(results.a.stderr, '');
  assert.equal(results.a.status, 0);
  const source = readFileSync(built.a, 'utf8');
  assert.match(
    source,
    /^\/\/ Generated by apps\/mobile\/scripts\/build-strudel\.mjs\. Do not edit/,
  );
  assert.match(source, /pnpm --filter mobile run build:strudel/);
  assert.match(source, /@strudel\/web 1\.3\.0, licensed AGPL-3\.0-or-later/);
  const { STRUDEL_HTML, STRUDEL_BUNDLE_VERSION } = await importModule(source);
  const hash = createHash('sha256').update(STRUDEL_HTML).digest('hex').slice(0, 8);
  assert.equal(STRUDEL_BUNDLE_VERSION, `1.3.0-${hash}`);
  assert.match(STRUDEL_HTML, /^<!doctype html>/);
  assert.match(STRUDEL_HTML, /initStrudel/);
  const notice = '/*! @strudel/web 1.3.0 | AGPL-3.0-or-later | https://codeberg.org/uzu/strudel */';
  assert.ok(scriptBody(STRUDEL_HTML).trimStart().startsWith(notice));
  assert.doesNotThrow(() => new vm.Script(scriptBody(STRUDEL_HTML)), 'the real bundle parses');
});

test('No network in the page: the policy is exact and nothing loads from a URL', async () => {
  const { STRUDEL_HTML } = await importModule(readFileSync(built.a, 'utf8'));
  const policies = [
    ...STRUDEL_HTML.matchAll(/http-equiv="Content-Security-Policy"\s+content="(.*?)"/g),
  ];
  assert.deepEqual(
    policies.map((match) => match[1]),
    [POLICY],
  );
  assert.doesNotMatch(STRUDEL_HTML, /<script[^>]*\ssrc\s*=/i);
  assert.doesNotMatch(STRUDEL_HTML, /<link/i);
  assert.equal(STRUDEL_HTML.match(/<script/gi)?.length, 1);
  assert.equal(STRUDEL_HTML.match(/<\/script/gi)?.length, 1);
  assert.ok(!STRUDEL_HTML.includes(MOBILE), 'no absolute path in the page');
});

test('Repeatable: two builds are byte-identical', () => {
  assert.equal(results.b.status, 0);
  assert.equal(results.b.stderr, '');
  assert.ok(readFileSync(built.a).equals(readFileSync(built.b)));
});

test('the bundle cannot break out of the script element or the string', async () => {
  const values = ['`', '${x}', '\\', '</script>', '</SCRIPT >', ' ', ' '];
  const bundle = `globalThis.values = ${JSON.stringify(values)};
globalThis.tpl = \`\${'a'}</script>\\\`\`; // </script> in a comment`;
  const html = renderHtml(TEMPLATE, bundle);
  assert.equal(html.match(/<\/script/gi)?.length, 1);
  const sandbox = {};
  vm.runInNewContext(scriptBody(html), sandbox);
  // Spread into this realm's Array: deepEqual compares prototypes, and the sandbox has its own.
  assert.deepEqual([...sandbox.values], values);
  assert.equal(sandbox.tpl, 'a</script>`');
  const source = renderModule({ html, version: '1.3.0', license: 'AGPL-3.0-or-later' });
  assert.ok(!source.includes('\u2028'), 'U+2028 is escaped in the module source');
  const { STRUDEL_HTML } = await importModule(source);
  assert.equal(STRUDEL_HTML, html);
});

test('a bundle with <!-- or <script is refused, not rewritten', () => {
  for (const text of ['<!--', '<script', '<SCRIPT type="x">']) {
    assert.throws(() => renderHtml(TEMPLATE, `globalThis.x = ${JSON.stringify(text)};`), {
      message: NOT_EMBEDDABLE.slice('build-strudel: '.length, -1),
    });
  }
});

test('a bundle that does not parse is refused', () => {
  assert.throws(() => renderHtml(TEMPLATE, 'globalThis.x = ;'), {
    message: /^the bundled script does not parse: [^\n]+$/,
  });
});

test('Build failure: an unembeddable bundle fails the build and writes nothing', () => {
  for (const [name, text] of [
    ['comment', '<!--'],
    ['script', '<script'],
  ]) {
    const entry = join(work, `${name}-entry.js`);
    writeFileSync(entry, `globalThis.x = ${JSON.stringify(text)};\n`);
    const out = join(work, `${name}-out`, 'strudelHtml.ts');
    const result = run('--out', out, '--entry', entry);
    assert.equal(result.status, 1);
    assert.equal(result.stderr, NOT_EMBEDDABLE);
    assert.ok(!readdirSync(work).includes(`${name}-out`));
  }
});

test('Build failure: a resolution error other than not-found is not a quiet skip', () => {
  const corrupt = join(work, 'corrupt');
  mkdirSync(join(corrupt, 'node_modules', 'esbuild'), { recursive: true });
  writeFileSync(join(corrupt, 'node_modules', 'esbuild', 'package.json'), '{ "main": ');
  const out = join(work, 'corrupt-out', 'strudelHtml.ts');
  const result = run('--postinstall', '--out', out, '--resolve-from', corrupt);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /^build-strudel: resolve failed: Invalid package config [^\n]+\n$/);
  assert.ok(!readdirSync(work).includes('corrupt-out'));
});

test('Build failure: @strudel/web cannot be resolved', () => {
  const empty = join(work, 'empty');
  const out = join(work, 'missing', 'strudelHtml.ts');
  mkdirSync(empty);
  const result = run('--out', out, '--resolve-from', empty);
  assert.equal(result.status, 1);
  assert.equal(result.stderr, NOT_FOUND);
  assert.ok(!readdirSync(work).includes('missing'));
});

test('On install without devDependencies: skipped with one line, install not failed', () => {
  const empty = join(work, 'no-dev');
  const out = join(work, 'no-dev-out', 'strudelHtml.ts');
  mkdirSync(empty);
  const result = run('--postinstall', '--out', out, '--resolve-from', empty);
  assert.equal(result.status, 0);
  assert.equal(result.stderr, NOT_BUILT);
  assert.ok(!readdirSync(work).includes('no-dev-out'));
});

test('On install with esbuild but no @strudel/web: the install fails', () => {
  const partial = join(work, 'partial');
  mkdirSync(join(partial, 'node_modules'), { recursive: true });
  symlinkSync(
    join(MOBILE, '..', '..', 'node_modules', 'esbuild'),
    join(partial, 'node_modules', 'esbuild'),
  );
  const result = run(
    '--postinstall',
    '--out',
    join(work, 'partial-out', 'x.ts'),
    '--resolve-from',
    partial,
  );
  assert.equal(result.status, 1);
  assert.equal(result.stderr, NOT_FOUND);
});

test('an unexpected error names the failed step in one line and leaves no temporary file', () => {
  const out = join(work, 'taken', 'strudelHtml.ts');
  mkdirSync(join(out, 'inside'), { recursive: true });
  const result = run('--out', out);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /^build-strudel: write failed: [^\n]+\n$/);
  assert.deepEqual(readdirSync(join(work, 'taken')), ['strudelHtml.ts']);
});

test('an unknown option fails in one line', () => {
  const result = run('--outt', 'x');
  assert.equal(result.status, 1);
  assert.match(result.stderr, /^build-strudel: arguments failed: [^\n]+\n$/);
});
